// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package databases

// Injectors from injector.go:

func InitializedDatabaseRepository() *DatabaseRepository {
	databaseMySQL := NewDatabaseMySQL()
	databasePgSQL := NewDatabasePgSQL()
	databaseMSSQL := NewDatabaseMSSQL()
	databaseRepository := NewDatabaseRepository(databaseMySQL, databasePgSQL, databaseMSSQL)
	return databaseRepository
}
